### ISSUE TITLE
Configuration files do not identify themselves as "Managed by Puppet, do not edit."

### ISSUE THREAD

**Issue by bschonec** [voxpupuli/puppet-rsyslog#202]
/etc/rsyslog.d/ files do not have "Managed by Puppet" or similar at the beginning of the file to identify them as being Puppet managed.

Shouldn't they have that notice like (pretty much) every other Puppet managed file resource?

**Comment by smoeding** [comment]
The `concat` type supports a `warn` parameter. Setting the parameter to `true` will add such a message to the file create by `concat`. Since pretty much all config files are created as `concat` resources, it seems to be as easy as adding the parameter `warn => true` to the two `concat` resources in `rsyslog::generate_concat`.

**Comment by bschonec** [comment]
#214

**Comment by spotter-puppet** [comment]
Seems this issue should be closed fixed.

**Comment by bschonec** [comment]
For reference: #214
